Only install the ghostty terminfo
https://github.com/NixOS/nixpkgs/issues/568896 leads to:

```
error: builder for '/nix/store/lp045kfxp62a3wq1caiy5x9aq5lwgibf-rxvt-unicode-unwrapped-9.31.drv' failed with exit code 2;
       last 25 log lines:
       >       |       ~~~~~^~~~~~~~~~~~~~~~~~~~
       >   • there are 5 candidates
       >     • candidate 1: 'constexpr __gnu_cxx::__promoted_t<_Tp, _Up, _Vp> std::lerp(_Tp, _Up, _Vp) [with _Tp = short unsigned int; _Up = short unsigned int; _Vp = int; __gnu_cxx::__promoted_t<_Tp, _Up, _Vp> = double]'
       >       /nix/store/5q6bdxkp7lc70gn9mnf4yiybrx8ry5xq-gcc-16.2.0/include/c++/16.2.0/cmath:3870:5:
       >        3870 |     lerp(_Tp __x, _Up __y, _Vp __z) noexcept
       >             |     ^~~~
       >     • candidate 2: 'T lerp(T, U, P) [with T = short unsigned int; U = short unsigned int; P = int]'
       >       ./rxvtutil.h:24:1:
       >          24 | lerp (T a, U b, P p)
       >             | ^~~~
       >     • candidate 3: 'constexpr long double std::lerp(long double, long double, long double)'
       >       /nix/store/5q6bdxkp7lc70gn9mnf4yiybrx8ry5xq-gcc-16.2.0/include/c++/16.2.0/cmath:3865:3:
       >        3865 |   lerp(long double __a, long double __b, long double __t) noexcept
       >             |   ^~~~
       >     • candidate 4: 'constexpr double std::lerp(double, double, double)'
       >       /nix/store/5q6bdxkp7lc70gn9mnf4yiybrx8ry5xq-gcc-16.2.0/include/c++/16.2.0/cmath:3861:3:
       >        3861 |   lerp(double __a, double __b, double __t) noexcept
       >             |   ^~~~
       >     • candidate 5: 'constexpr float std::lerp(float, float, float)'
       >       /nix/store/5q6bdxkp7lc70gn9mnf4yiybrx8ry5xq-gcc-16.2.0/include/c++/16.2.0/cmath:3857:3:
       >        3857 |   lerp(float __a, float __b, float __t) noexcept
       >             |   ^~~~
       > make[1]: *** [Makefile:61: rxvttoolkit.o] Error 1
       > make[1]: Leaving directory '/build/rxvt-unicode-9.31/src'
       > make: *** [Makefile:37: all] Error 1
       For full logs, run:
         nix log /nix/store/lp045kfxp62a3wq1caiy5x9aq5lwgibf-rxvt-unicode-unwrapped-9.31.drv
error: 1 dependencies of derivation '/nix/store/vllldfmxwan778lcr2p7kn8fqbg4k5pi-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vz293li327dm6bg7g6v0kv382ab6pq0h-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/kwaiiv5whws9vzlmw7aiaclbmrwn5ga6-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/5h3xg4wgifjf29xn532in4ccq6yx18dp-nixos-system-gargoyle-26.11.20261001.c59305b.drv' failed to build
```

Which is something we only really care about for the terminfo bits so we
stop compiling every terminal emulator we know of.